---
name: Release Drafter

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master

jobs:
  workflows:
    uses: hassio-addons/workflows/.github/workflows/release-drafter.yaml@main
